classes/Http/Form/ResetForm.php
<?php
namespace OpenCFP\Http\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints as Assert;

class ResetForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('password', 'repeated', [
                'constraints' => [
                    new Assert\NotBlank(),
                    new Assert\Length(['min' => 5]), ],
                'type' => 'password',
                'first_options' => ['label' => 'Password (minimum 5 characters)'],
                'second_options' => ['label' => 'Password (confirm)'],
                'first_name' => 'password',
                'second_name' => 'password2',
                'invalid_message' => 'Passwords did not match', ])
            ->add('user_id', 'hidden')
            ->add('reset_code', 'hidden')
            ->getForm();
    }

    public function getName()
    {
        return 'reset';
    }
}

templates/_flash.twig
{% block flash %}
  {% if flash is defined and flash is not empty %}
    {% set flash_type = (flash.type == 'error') ? 'danger' : flash.type %}
    <div class="alert alert-{{ flash_type }}">
      {% if flash.short is not empty %}<strong>{{ flash.short }}:</strong> {% endif %}
      {% autoescape false %}{{ flash.ext }}{% endautoescape %}
    </div>
  {% endif %}
{% endblock flash %}

templates/_header.twig
<header class="header">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <img data-src="/assets/img/logo_round.svg" class="svg-inject event-logo" alt="Event Logo">
                </div>
                <div class="col-md-9">
                    {% if cfp_open %}
                        <h1 class="headline headline-alpha">Call For Papers Now Open!</h1>
                        <h3 class="headline headline-alpha">Submissions accepted until {{ site.enddate }}</h3>
                    {% else %}
                        <h1 class="headline headline-alpha">
                            {% if site.show_submission_count %}
                                Call for Papers ended with {{ number_of_talks }} Submissions!
                            {% else %}
                                Call for Papers has ended!
                            {% endif %}
                        </h1>
                        <h3 class="headline headline-alpha">Submissions were accepted until {{ site.enddate }}</h3>
                    {% endif %}
                    <p>
                        {% if cfp_open %}<a class="btn-opencfp btn-opencfp-medium btn-opencfp--outlined" href="{{ url('user_new') }}">Register Now</a>{% endif %}
                        <a class="btn-opencfp btn-opencfp-medium btn-opencfp--primary" href="{{ url('dashboard') }}">View Submissions</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<section class="section section--light">
    <div class="container">
        <div class="row">
            {% if site.event_location is defined and site.date_format is defined %}
            <div class="col-md-8"><h3 class="headline headline--alpha">
                {{ site.title }} is  on {{ site.arrival|date(site.date_format) }} to {{ site.departure|date(site.date_format) }} in {{ site.event_location }}
            </h3></div>
            {%  else %}
                <div class="col-md-8"><h3 class="headline headline--alpha">For More Information About The Conference</h3></div>
            {% endif %}
            <div class="col-md-4 text-right"><a href="{{ site.eventurl }}" class="btn-opencfp btn-opencfp-medium btn-opencfp--light">Visit Conference Site</a></div>
        </div>
    </div>
</section>

templates/_marketing.twig
<div class="container">
    <div class="section row">
        <div class="col-md-6">
            <h3 class="headline headline--beta">Got a talk idea? We want to see it!</h3>
            <p>
                We’re pleased to announce our conference, {{ site.title }} should be
                one of the best PHP conferences where community members from around
                the world come together to learn and share information about the latest
                trends and technologies in professional PHP development.
            </p>
        </div>
        <div class="col-md-6">
            <h3 class="headline headline--beta">Speaker Package</h3>
            <p>
                We know speakers are key to the success of a conference and hope
                you will submit a talk.  In appreciation of your efforts, our speaker
                compensation package includes:

                <p><a href="{{ url('speaker_package') }}">View Full Speaker Package</a></p>
            </p>
        </div>
    </div>
</div>

<section class="section section--primary">
    <div class="container">
        <h2 class="headline headline--beta headline--centered">Diversity Matters!</h2>
        <p>
            {{ site.title }} is committed to creating a conference that is as inclusive as possible.
            We want to showcase talent available around the U.S. and welcome international submissions as well.
        </p>
        <p>
            We are also committed to ensuring the conference is a place
            where ideas are exchanged, old friends get together, new friends meet and <strong>harassment
            is not tolerated</strong>. We expect speakers, attendees and sponsor representatives to be
            professional and courteous to each other. We reserve the right to remove, without refund,
            ANY attendee (speaker or otherwise) who is unable to adhere to this policy.
        </p>
    </div>
</section>

templates/dashboard.twig
{% extends "layouts/dashboard.twig" %}
{% block scripts %}
{{ parent() }}
<script type="text/javascript">
function deleteTalk(tid) {
    $.ajax({
        type: "POST",
        url: "/talk/delete",
        data: "tid=" + tid + "&user_id=" + {{ user.id }},
        success: function(data, textStatus, jqXHR) {
            if (data.delete == 'ok') {
                alert("Deleted talk!");
                $("#talk-"+tid).remove();
            } else if (data.delete == 'no-user') {
                alert("You must be logged in to delete talks")
            } else {
                alert("Unable to delete talk");
            }
        }
    });
}
</script>
{% endblock %}
{% block content %}
    <span class="pull-right">Welcome <strong>{{ profile.name }}</strong></span>

    <h2 class="headline">My Profile</h2>
    <div class="row">
        <div class="col-md-3">
            <p>
                {% if profile.photo is not empty %}
                    <img src="{{ uploads(profile.photo) }}" class="profile-photo img-responsive" />
                {% else %}
                    <img src="{{ assets('img/dummyphoto.jpg') }}" class="profile-photo img-responsive" />
                {% endif %}
            </p>
            <p><a href="{{ url('user_edit', { id: user.id }) }}" class="btn btn-success btn-block">Edit Profile</a></p>
        </div>
        <div class="col-md-9">
            <br />
            <strong>Name:</strong> {{ profile.name }}
            {% if profile.twitter %}
                <a href="https://twitter.com/@{{ profile.twitter }}" title="{{ profile.name }} on Twitter">@{{ profile.twitter }}</a>
            {% endif %}<br />
            <strong>Company:</strong> {{ profile.company }}<br />
            {% if site.online_conference == false %}
            <strong>Airport:</strong> {{ profile.airport }}<br />
            {% endif %}
            <strong>Bio:</strong> {{ profile.bio|striptags|markdown }}<br /><br />
            <strong>Other Info:</strong> {{ profile.info|striptags|markdown }}<br /><br />

            {% if site.online_conference == false %}
            <strong>Need Transportation:</strong> {% if profile.transportation == '1' %} Yes {% else %} No {% endif %}<br />
            <strong>Need Hotel:</strong> {% if profile.hotel == '1' %} Yes {% else %} No {% endif %}
            {% endif %}
        </div>
    </div>

    <h2 class="headline">My Talks</h2>
    {% if profile.talks is not empty %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Talk Name</th>
                <th>Type</th>
                <th>Category</th>
                <th>Created On</th>
                <th>&nbsp;</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
        {% for talk in profile.talks %}
            <tr id="talk-{{ talk.id }}">
                <td><b><a href="{{ url('talk_view', { id: talk.id }) }}">{{ talk.title|raw }}</a></b></td>
                <td>{{ talk.type }}</td>
                <td>{{ talk.category }}</td>
                <td>{{ talk.created_at|date("F jS \\a\\t g:ia T") }}</td>
                {% if cfp_open %}
                    <td><a href="{{ url('talk_edit', { id: talk.id }) }}">Edit</a></td>
                {% else %}
                    <td><a href="{{ url('talk_view', { id: talk.id }) }}">View</a></td>
                {% endif %}
                <td><a href="#" onClick="deleteTalk('{{ talk.id }}');return false;">Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        You currently have no talks submitted.
    {% endif %}
    <p><a class="btn btn-success" href="{{ url('talk_new') }}">Submit a talk</a></p>
{% endblock %}

templates/home.twig
{% extends "layouts/default.twig" %}
{% block content %}
    {% include "_marketing.twig" %}
{% endblock %}

templates/ideas.twig
{% extends "layouts/default.twig" %}
{% block content %}
<div class="container">
    <h2 class="headline--beta">Call for Papers Talk Ideas</h2>
    <p>
        {{ site.title }} is not limited to just PHP-related talks. There have been
        sessions covering a wide range of topics supporting PHP developers and DevOps
        as well, and we encourage you to "think outside the box" to come up with your
        own unique topics.
    </p>
    <p>
        Due to financial constraints most conferences tend to pick speakers to present
        multiple talks. Therefore <strong>it is advisable to submit a few talk ideas, not just one.</strong>
        By submitting a single talk you may lessen your chances of being selected.
    </p>
    <p>
        To get the ideas flowing, here's a few suggestions:
    </p>
    <ul>
        <li>Virtualization and environments</li>
        <li>Javascript</li>
        <li>Alternate PHP run-times</li>
        <li>PHP internals</li>
        <li>Development principles</li>
        <li>Security</li>
        <li>Mobile-first design</li>
        <li>Testing (unit, functional, etc.)</li>
        <li>Version control</li>
        <li>User Experience/Usability</li>
        <li>Building APIs (REST, SOAP, whatever)</li>
        <li>Continuous Integration</li>
        <li>Framework-related topics</li>
        <li>Professional development</li>
    </ul>
</div>
{% endblock %}

templates/login.twig
{% extends "layouts/dashboard-nowrap.twig" %}
{% block content %}
  <div class="module module--constrained">
    <div class="module__header">Login</div>
    <div class="module__body">
      {% include "forms/_login.twig" %}
    </div>
    <div class="module__footer">
      <div class="row">
        <div class="col-md-8">
          <h4 class="headline--beta">Don't have an account yet?</h4>
        </div>
        <div class="col-md-4 text-right">
          <a href="{{ url('user_new') }}" class="btn-opencfp btn-opencfp-small btn-success">Register Now</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block js %}
    <script src="js/login.js"></script>
{% endblock %}

templates/package.twig
{% extends "layouts/default.twig" %}
{% block content %}
<div class="container">
    <h2 class="headline--beta">{{ site.title }} Speaker Information</h2>
    <p>
        We're committed to bringing together some of the best speakers from all around the
        world to share their knowledge with you here. We provide a travel and
        accommodation package to all selected speakers to help make this possible.
    </p>
    <h4 class="headline--alpha">About the event</h4>
    <p>
        Speakers will be provided with a projector, a wireless lapel microphone and a screen
        for their presentation (size depends on the room). Speakers should bring any equipment
        they need to connect to projectors (VGA). It is also suggested that you reduce your
        dependency on the in-house internet connection as possible.
    </p>
    <p>
        When the Call for Papers closes, the organizers will sort through the submissions, making
        their selections. Speakers will be notified as soon as the selection process has been completed.
    </p>
    <h4 class="headline--alpha">This year's package</h4>
    <p>
        Our speaker package for this year's event includes:
    </p>
    <ul>
        <li>Full conference pass</li>
        <li>Access to conference tutorials (lunch not included)</li>
        <li>For speakers remote to the Area:</li>
        <ul>
            <li>Complimentary airfare/travel (according to conference policy)</li>
            <li>2 complimentary hotel nights (additional 1 hotel night for speakers presenting a tutorial)</li>
        </ul>
        <li>Lunch, receptions and activities included in regular conference</li>
        <li>We'll pick you up and drop you off to/from the airport so you don't have to worry about it.</li>
    </ul>
    <p>
        International speakers are encouraged to <a href="/">submit their ideas</a>, but because of budget restrictions,
        we can only accept a limited number of speakers from outside the country.
    </p>
    <h4 class="headline--alpha">Tips for Submission</h4>
    <p>
        We <i>strongly</i> encourage potential speakers to submit more than one submission on more than one topic. The
        more submissions you contribute, the more options you give us to pick you. Be sure your talk title and abstract
        define the exact topic you want to talk about and what you hope people will learn from the session. In previous
        years, some submissions sounded interesting but we just didn't have enough detail for them to make the final cut.
    </p>
</div>
{% endblock %}